# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-15 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=100)),
                ('local_name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='plant',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='pest',
        ),
        migrations.DeleteModel(
            name='Plant',
        ),
        migrations.AddField(
            model_name='disease',
            name='crop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Crop'),
        ),
        migrations.AddField(
            model_name='pest',
            name='crop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Crop'),
        ),
    ]
