# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-16 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='crop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Crop'),
        ),
    ]
