# Generated by Django 3.2.4 on 2021-06-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_post_crop'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='pest',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='images/'),
        ),
    ]
