# Generated by Django 3.2.4 on 2021-06-16 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210616_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='pesticide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.pesticide'),
        ),
    ]
