# Generated by Django 3.2.4 on 2021-06-17 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_shopproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopproduct',
            old_name='pesticide',
            new_name='pesticide_id',
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='pesticide_image',
            field=models.ForeignKey(db_column='image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pesticide_image', to='app.pesticide', to_field='image'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='pesticide_name',
            field=models.ForeignKey(db_column='pesticide_name', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pesticide_name', to='app.pesticide', to_field='name'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='shop_name',
            field=models.ForeignKey(db_column='name', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_name', to='app.shop', to_field='name'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='crop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop', to='app.crop'),
        ),
        migrations.AlterField(
            model_name='pesticide',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', unique=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='pesticide',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
