# Generated by Django 3.2.4 on 2021-06-17 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210617_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopproduct',
            name='pesticide_image',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='pesticide_name',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='shop_name',
        ),
    ]
