# Generated by Django 3.2.4 on 2021-06-17 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210617_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopproduct',
            old_name='pesticide_id',
            new_name='pesticide',
        ),
    ]
