# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - sprinterspestcontrol

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://sprinterspestcontrolacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_dfea799e1469407bac21a88b7a200b5c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_61e4b1c82e20452e99800aa9a49856cd }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: sprinterspestcontrolacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_dfea799e1469407bac21a88b7a200b5c }}/sprinterspestcontrolc8fe:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'sprinterspestcontrol'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_77be6d5b9a7b49469bc537b1cda27047 }}
        images: 'sprinterspestcontrolacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_dfea799e1469407bac21a88b7a200b5c }}/sprinterspestcontrolc8fe:${{ github.sha }}'